### ISSUE TITLE
一些改进建议

### ISSUE THREAD

**Issue by hiberabyss** [mpco/Alfred3-workflow-recent-documents#1]
这个想法很赞, 感谢作者! 感觉还有下面这些地方可以改进一下:

1. 增加对 Microsoft Office 系列软件的支持, 他们 menu 里的名字叫 "打开最近的文件";
2. 支持按拼音搜索中文字符.

**Comment by mpco** [comment]
已更新：
1. 支持 Microsoft Office 2016
2. 支持拼音搜索中文字符


https://github.com/mpco/Alfred3-workflow-recent-documents/releases/tag/2.5
