### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by tixo** [mpco/Alfred3-workflow-recent-documents#12]
osx version:10.14.6
![20200223134714](https://user-images.githubusercontent.com/3055861/75104348-1c8cab80-5643-11ea-804e-1c8f763c07f4.jpg)
could not find target file from my folder
![1](https://user-images.githubusercontent.com/3055861/75104397-89a04100-5643-11ea-97c5-b682ddcdf1eb.jpg)

**Comment by mpco** [comment]
You can try to delete ( or backup to other folder ) the files with `sfl` extension, then restart your mac, then try this workflow.

**Comment by mpco** [comment]
Long time no reply.
