### ISSUE TITLE
office中使用rr无效

### ISSUE THREAD

**Issue by zhenghangezh** [mpco/Alfred3-workflow-recent-documents#16]
word, excel, powerpoint里使用rr都不行了

**Comment by zhenghangezh** [comment]
![image](https://user-images.githubusercontent.com/25739317/110942489-d650da00-8374-11eb-8388-a53e1e297fb5.png)

**Comment by mpco** [comment]
试试新版本 https://github.com/mpco/AlfredWorkflow-Recent-Documents/releases/tag/2.16
