### ISSUE TITLE
symbol not found error

### ISSUE THREAD

**Issue by Blackvz** [mpco/Alfred3-workflow-recent-documents#18]
I get the following error:
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/12122294/111708108-888d1380-8845-11eb-9c6d-f471a6faf662.png">

I work on a apple silicon device (MacOS Big Sur). Some ideas about that problem?

**Comment by xillllite** [comment]
I have the same problem. I solve it by replacing mac_alias with the latest version. And it works.

**Comment by Blackvz** [comment]
> I have the same problem. I solve it by replacing mac_alias with the latest version. And it works.

I am not so fit in python. Can you explain that please?

**Comment by Blackvz** [comment]
> > I have the same problem. I solve it by replacing mac_alias with the latest version. And it works.
> 
> I am not so fit in python. Can you explain that please?

Detailed solution can be found here: https://github.com/mpco/AlfredWorkflow-Recent-Documents/issues/19

Still not working for me.
