### ISSUE TITLE
Please upgrade,求更新，macOS 12.0版本下无法适用“rd，rr”

### ISSUE THREAD

**Issue by HomelandScenery** [mpco/Alfred3-workflow-recent-documents#22]
macOS升级至12.0 Monterey 后，无法使用最近文档，请作者更新，谢谢！
After upgrading MacOS to 12.0 Monterey,I can't use the recent documents. Please upgrade,  Thank you!

**Comment by MarkusLee705** [comment]
Experiencing the same problem here.. An upgrade would be much much appreciated!

**Comment by Miaoyifei-mz** [comment]
同求更新，12.0版本，rd,rr 无法使用

**Comment by glve1027** [comment]
Same issue.

**Comment by HomelandScenery** [comment]
![image](https://user-images.githubusercontent.com/19407813/145237877-1a1e8146-24db-46e9-a06e-f2132b7b9b19.png)
右键打开```Recent Documents / Apps```，在Finder中找到info.plist文件，然后```[[ $macOSVersion == 11.* ]] ```之前加入```[[ $macOSVersion == 12.* ]] ||```，共三处，保存后即可。
Open in Finder, find the```info.plist``` file, then add  ```[[ $macOSVersion == 12.* ]] ||``` before ```[[ $macOSVersion == 11.* ]] ``` in the file, save and run. Good luck!
![image](https://user-images.githubusercontent.com/19407813/145238924-13c1d20c-c8dd-4c7e-9d76-24cbc8e39c7e.png)

**Comment by Miaoyifei-mz** [comment]
您好，修改过后 `rd` 和 `ra` 仍然无法使用。

**这个是输入 `rd` 之后的报错信息**
```
[19:00:00.163] Logging Started...
[19:00:02.917] Recent Documents / Apps[Script Filter] Queuing argument '(null)'
[19:00:03.119] Recent Documents / Apps[Script Filter] Script with argv '(null)' finished
[19:00:03.122] ERROR: Recent Documents / Apps[Script Filter] Code 1: Traceback (most recent call last):
  File "main.py", line 209, in <module>
    allItemsLinkList.extend(itemsLinkList)
TypeError: 'NoneType' object is not iterable
[19:00:03.123] Recent Documents / Apps[Script Filter] [Errno 1] Operation not permitted: '/Users/zhuangzhu/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentDocuments.sfl2'
[19:00:03.123] ERROR: Recent Documents / Apps[Script Filter] JSON error: Invalid value around line 1, column 1. in JSON:
[Errno 1] Operation not permitted: '/Users/zhuangzhu/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentDocuments.sfl2'
```
**这个是输入 `ra` 之后的报错信息**
```
[19:05:58.528] Recent Documents / Apps[Script Filter] Queuing argument '(null)'
[19:05:58.676] Recent Documents / Apps[Script Filter] Script with argv '(null)' finished
[19:05:58.678] ERROR: Recent Documents / Apps[Script Filter] Code 1: Traceback (most recent call last):
  File "main.py", line 209, in <module>
    allItemsLinkList.extend(itemsLinkList)
TypeError: 'NoneType' object is not iterable
[19:05:58.679] Recent Documents / Apps[Script Filter] [Errno 1] Operation not permitted: '/Users/zhuangzhu/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentApplications.sfl2'
[19:05:58.680] ERROR: Recent Documents / Apps[Script Filter] JSON error: Invalid value around line 1, column 1. in JSON:
[Errno 1] Operation not permitted: '/Users/zhuangzhu/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentApplications.sfl2'
```

**Comment by HomelandScenery** [comment]
我也不是程序员，只是参考作者去年对MacOS升级时对代码的修改，增加了三处```[[ $macOSVersion == 12.* ]]```，如果不能解决，只能等专业人员来更新这个workflow。😁

**Comment by Miaoyifei-mz** [comment]
今天突然发现，Alfred的磁盘完全访问权限在MacOS12里被取消了，重新开启后问题就解决了。

**Comment by chenshuaikang** [comment]
> 您好，修改过后 `rd` 和 `ra` 仍然无法使用。
> 
> **这个是输入 `rd` 之后的报错信息**
> 
> ```
> [19:00:00.163] Logging Started...
> [19:00:02.917] Recent Documents / Apps[Script Filter] Queuing argument '(null)'
> [19:00:03.119] Recent Documents / Apps[Script Filter] Script with argv '(null)' finished
> [19:00:03.122] ERROR: Recent Documents / Apps[Script Filter] Code 1: Traceback (most recent call last):
>   File "main.py", line 209, in <module>
>     allItemsLinkList.extend(itemsLinkList)
> TypeError: 'NoneType' object is not iterable
> [19:00:03.123] Recent Documents / Apps[Script Filter] [Errno 1] Operation not permitted: '/Users/zhuangzhu/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentDocuments.sfl2'
> [19:00:03.123] ERROR: Recent Documents / Apps[Script Filter] JSON error: Invalid value around line 1, column 1. in JSON:
> [Errno 1] Operation not permitted: '/Users/zhuangzhu/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentDocuments.sfl2'
> ```
> 
> **这个是输入 `ra` 之后的报错信息**
> 
> ```
> [19:05:58.528] Recent Documents / Apps[Script Filter] Queuing argument '(null)'
> [19:05:58.676] Recent Documents / Apps[Script Filter] Script with argv '(null)' finished
> [19:05:58.678] ERROR: Recent Documents / Apps[Script Filter] Code 1: Traceback (most recent call last):
>   File "main.py", line 209, in <module>
>     allItemsLinkList.extend(itemsLinkList)
> TypeError: 'NoneType' object is not iterable
> [19:05:58.679] Recent Documents / Apps[Script Filter] [Errno 1] Operation not permitted: '/Users/zhuangzhu/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentApplications.sfl2'
> [19:05:58.680] ERROR: Recent Documents / Apps[Script Filter] JSON error: Invalid value around line 1, column 1. in JSON:
> [Errno 1] Operation not permitted: '/Users/zhuangzhu/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentApplications.sfl2'
> ```

系统偏好设置-->安全性与隐私-->隐私--完全磁盘访问权限-->勾选Alfred
以上即可解决上述问题。
