### ISSUE TITLE
Please upgrade,求更新，macOS 12.3版本下无法适用“rd“

### ISSUE THREAD

**Issue by HomelandScenery** [mpco/Alfred3-workflow-recent-documents#24]
macOS升级至12.3 Monterey 后，无法使用”rd“ 最近文档，请作者更新，谢谢！
After upgrading MacOS to 12.3 Monterey,I can't use the recent documents. Please upgrade, Thank you!

**Comment by Miaoyifei-mz** [comment]
Me too

**Comment by mpco** [comment]
Duplicate of #25
