### ISSUE TITLE
Don't compat macOS 12.3

### ISSUE THREAD

**Issue by tianma8023** [mpco/Alfred3-workflow-recent-documents#25]
Because macOS 12.3 removed the bundle of Python 2.7 

So the command:
```shell
/usr/bin/python xxx
```
causes the error like this:
```shell
/usr/bin/python: No such file or directory
```

## reference
- [Making Python 2 Workflows work on macOS Monterey 12.3 and above](https://www.alfredforum.com/topic/17941-making-python-2-workflows-work-on-macos-monterey-123-and-above/#comments)
- [Python 2 Workflows on macOS Monterey](https://www.alfredapp.com/help/kb/python-2-monterey/)

**Comment by mpco** [comment]
Please try this version, test all features and let me know the result. 
[Recent Documents-V2.19.zip](https://github.com/mpco/AlfredWorkflow-Recent-Documents/files/8266757/Recent.Documents-V2.19.zip)

**Comment by tianma8023** [comment]
@mpco After my test, all features are OK.

**Comment by HomelandScenery** [comment]
> 

Me too.
