### ISSUE TITLE
macos 13.2.1无法使用

### ISSUE THREAD

**Issue by GladioFeng** [mpco/Alfred3-workflow-recent-documents#33]
不管是rr rd 都无法使用呢？求作者大大修复一下😭😭😭
<img width="776" alt="image" src="https://user-images.githubusercontent.com/100987925/222079269-5ebd6df6-ecd3-474a-8839-859a1519b201.png">

**Comment by kaqijiang** [comment]
可以试试这个，我自己用python3重写了大部分的日常使用工具。Alfred5 +Python3就行
https://github.com/kaqijiang/MyToolBox-AlfredWorkflow

**Comment by lyhxiangyang** [comment]
我升级到14.1发现无法使用，解决方式如下：

打开debug模式查看报错信息

<img width="1117" alt="image" src="https://github.com/mpco/AlfredWorkflow-Recent-Documents/assets/23033852/df2667cb-2335-4435-899c-d3d049f31eb9">

打开对应的main.py

<img width="885" alt="image" src="https://github.com/mpco/AlfredWorkflow-Recent-Documents/assets/23033852/eef231c1-55bf-4533-a870-019b01e1dc7b">

修改之后就可以使用了

<img width="718" alt="image" src="https://github.com/mpco/AlfredWorkflow-Recent-Documents/assets/23033852/fd61ec9e-c820-48cf-a66a-533fcf0cb0a6">

**Comment by lyhxiangyang** [comment]
<img width="804" alt="image" src="https://github.com/mpco/AlfredWorkflow-Recent-Documents/assets/23033852/b23c2d67-00bd-422d-9a0e-993c2e939adb">

这个rr 命令还需要改一个地方

**Comment by zcysxy** [comment]
@lyhxiangyang Your fix works for me! Maybe you can consider submitting a pull request : )

**Comment by Miaoyifei-mz** [comment]
<img width="804" alt="image" src="https://github.com/mpco/AlfredWorkflow-Recent-Documents/assets/60280844/7769eee3-08f1-4e59-b29f-b83cb9da0e2d">

rd 命令把 sfl2 改为 sfl3

**Comment by HGHEW1769** [comment]
@lyhxiangyang ： 按照你上面更改，还是无法使用，RD和RA， 我用的苹果M2 Pro 芯片，操作系统是macOS Sonoma
版本14.4.1， 帮忙看一下如何解决，多谢

**Comment by lyhxiangyang** [comment]
> 看一下

debug一下，看看有什么报错信息吗
