### ISSUE TITLE
Fall back to Session.sublime_session for Sublime Text 3

### ISSUE THREAD

**Issue by ErikMinekus** [mpco/Alfred3-workflow-recent-documents#5]
`rr` sometimes fails for Sublime Text, because the _Auto Save Session.sublime_session_ file is deleted when you quit Sublime Text, and it's not recreated until you open Sublime Text and edit and save a file.

It would be nice if the workflow could fall back to _Session.sublime_session_ if _Auto Save Session.sublime_session_ doesn't exist.

**Comment by mpco** [comment]
You can try the new release https://github.com/mpco/Alfred3-workflow-recent-documents/releases/tag/2.6
