### ISSUE TITLE
can't find recent docs for IdeaIC2018.3

### ISSUE THREAD

**Issue by 1206lyp** [mpco/Alfred3-workflow-recent-documents#7]
find ~/Library/Containers and ~/Library/Application Support/IdeaIC2018.3, can't find the sharedfileslist

**Comment by mpco** [comment]
After researching, I found the history of PyCharm2018.1 should be stored in `~/Library/Preferences/PyCharm2018.1/options/recentProjectDirectories.xml`.

IdeaIC2018.3 should be the same as PyCharm2018.1.
