### ISSUE TITLE
Please add macOS 10.15 support

### ISSUE THREAD

**Issue by haakonstorm** [mpco/Alfred3-workflow-recent-documents#9]
# check macos version
macOSVersion=$(sw_vers -productVersion | cut -d '.' -f 1,2)
if [ "$macOSVersion" = "10.14" ] || [ "$macOSVersion" = "10.13" ]; then
    MRUfileExt="sfl2"
elif [ "$macOSVersion" = "10.11" ] || [ "$macOSVersion" = "10.12" ]; then
    MRUfileExt="sfl"
fi

**Comment by mpco** [comment]
I didn't upgrade to 10.15 and can't test it for a while, wait for 10.15 final release. 
You can try changing 10.14 to 10.15 in the code.

**Comment by mpco** [comment]
This workflow has been updated for macOS 10.15. https://github.com/mpco/AlfredWorkflow-Recent-Documents/releases/tag/2.11
